[network]
n3h_path = "/usr/local/share/n3h"  # change this to your path!
n3h_persistence_path = "/tmp"
bootstrap_nodes = []

[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "sandwich--------------------------------------------------------------------------AAAEqzh28L"
key_file = "holo_tester.key"

[[dnas]]
id = "holotw_app_dna"
file = "bundle.json"
hash = "QmWoL2nMQnmihKp4uBgFpgdJCe9PYN3jYg5i3SJYLvjnsn"

[[instances]]
id = "test-instance"
dna = "holotw_app_dna"
agent = "test_agent1"
[instances.storage]
#type = "file"
#path = "./tmp-storage1"
type = "memory"

[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3400
[[interfaces.instances]]
id = "test-instance"

[logger]
type = "debug"
  [[logger.rules.rules]]
    pattern = "^err/"
    color = "red"
  [[logger.rules.rules]]
    pattern = "^debug/dna"
    color = "white"
  [[logger.rules.rules]]
    pattern = ".*"
